version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes: #ダウンロードしたファイルの直下にPathを変更
      - C:/Users/wansu/IdeaProjects/setReact:/app
    ports: #本番用ポート番号
      - "8080:8080"