version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes: #ダウンロードしたファイルの直下にPathを変更
      - ../:/app
    ports:
      #本番用ポート番号
      - "8080:8080"
      #リモートデバック用
      - "5005:5005"

  db:
    image: postgres:latest
    container_name: sample_db_container
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ..\init_db:/docker-entrypoint-initdb.d