version: '3'

x-template: &flyway-template
  image: boxfuse/flyway:latest
  volumes:
    - ../src/main/resources/db/migration:/flyway/sql # マイグレーション用SQLファイルの格納先
    - ../src/main/resources/db/migration/conf:/flyway/conf # 設定ファイルの格納先
  depends_on:
    - db

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes: #ダウンロードしたファイルの直下にPathを変更
      - ../:/app
    ports:
      #本番用ポート番号
      - "8080:8080"
      #リモートデバック用
      - "5005:5005"

  db:
    image: postgres:latest
    container_name: sample_db_container
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ../src/main/resources/db/init_db:/docker-entrypoint-initdb.d

  flyway-clean:
    <<: *flyway-template
    command: clean

  flyway-migrate:
    <<: *flyway-template
    command: migrate

  flyway-info:
    <<: *flyway-template
    command: info




